source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'JIPHY' do
    pod 'RxSwift', '~> 3.0'
    pod 'RxCocoa', '~> 3.0'
    pod 'SnapKit', '~> 3.2.0'
    pod 'SDWebImage'
    pod 'SDWebImage/GIF'
end
