source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'JIPHY' do
    pod 'Alamofire', '~> 4.4'
    pod 'RxSwift', '~> 3.0'
    pod 'RxCocoa', '~> 3.0'
    pod 'ReactiveSwift'
    pod 'SnapKit', '~> 3.2.0'
    pod 'SwiftyGif'
end
